set_xmakever("2.6.3")

set_project("SoftwareRendering")

add_requires("spdlog")
add_requires("assimp")
add_requires("glad")
add_requires("glfw")
add_requires("glm")
add_requires("stb")

rule("CopyResource")
    after_build(function (target)
        os.cp("../Resource", path.join(target:targetdir(), "Resource"))
    end)

target("SoftwareRendering")
    set_kind("binary")
    set_languages("c++17")
    add_files("Src/**.cpp")
    add_headerfiles("Src/**.hpp")
    add_includedirs("Src/include/SoftwareRendering")
    add_includedirs("Src/include/SoftwareRendering/Shader")
    add_rules("mode.debug", "mode.release")
    add_rules("CopyResource")
    add_packages("spdlog")
    add_packages("assimp")
    add_packages("glad")
    add_packages("glfw")
    add_packages("glm")
    add_packages("stb")
