[package]
name = "sr"
version = "0.1.0" 
description = "sr"
license = "MIT"
edition = "2021"

[dependencies]
image = "0.24.5"
nalgebra = "0.31.4"
rayon = "1.6"
lazy_static = "1.4.0"
num-traits = "0.2.15"